In [9]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

# np.add() -> Adds corresponding elements.
print(np.add(a, b))

# np.subtract() -> Subtracts corresponding elements.
print(np.subtract(a, b))

# np.multiply() -> Multiplies corresponding elements.
print(np.multiply(a, b))


[11 22 33]
[ 9 18 27]
[10 40 90]


In [10]:

# np.floor_divide() -> Performs division and returns the floor value.
a1 = np.array([10, 20, 25])
b1 = [3,6,4]
print("\n",np.floor_divide(a1,b1))



 [3 3 6]


In [14]:
# np.mod() -> Returns the remainder after division.
print(np.mod(a1, b1))

# np.power() ->  Raises each element to a power.
a = np.array([2,3,4])
print(np.power(a,2))

[1 2 1]
[ 4  9 16]
