In [35]:
import numpy as np

data = np.array([10, 20, 30, 40, 50, 60])
data

# .reshape(rows, columns) ->   change the arrangement of an array without changing its data.
new_data = data.reshape(2, 3) #reshaped into 2 rows and 3 columns
new_data


array([[10, 20, 30],
       [40, 50, 60]])

In [36]:
sales = np.array([100, 200, 150, 300, 250, 400])

# -1 = NumPy, you calculate this dimension for me.
print(sales.reshape(3,-1))

# NumPy lets us perform calculations on an entire array at once.
# operations

print("\n",sales + 50)
print("\n",sales * 2)
print("\n", sales - 50)
print("\n", sales / 2)

[[100 200]
 [150 300]
 [250 400]]

 [150 250 200 350 300 450]

 [200 400 300 600 500 800]

 [ 50 150 100 250 200 350]

 [ 50. 100.  75. 150. 125. 200.]


In [37]:
# Aggregation: Take many values → calculate one useful result.

marks = np.array([70, 80, 90, 60, 100, 75, 70, 90])

print("\nSum: ", marks.sum())
print("\nAverage: ", marks.mean())
print("\nHighest: ", marks.max())
print("\nLowest: ", marks.min())





Sum:  635

Average:  79.375

Highest:  100

Lowest:  60


In [ ]:
#          Numpy Methods
print("\n\t\t IMPORTANT NUMPY METHODS:")

# Median = middle value after arranging values in sorted order.
print("\nMedian: ", np.median(marks))


# np.sort() is used to sort the values of a NumPy array.
print("\nOriginal (before sorting):  ",marks)
print("\nSorted (after sorting) : ",np.sort(marks))



cities = np.array(["Ahmedabad", "Bhavnagar", "Ahmedabad", "Delhi", "Bhavnagar"])

# np.unique -> find the unique values in an array.
print("\nUnique values: ",np.unique(cities))


# np.arange() -> used to create an array of numbers within a range.
num = np.arange(20,30,2) # start:20, end: 30 (not included, so 29), step: 2
num


# np.where(condition) is used to find the indexes where a condition is True.
# np.where() ->Returns the positions where the condition is True.

salary = np.array([20000, 35000, 50000, 18000, 60000])

print("\n ",np.where(salary > 30000))


# Filtering -> Returns the actual values that satisfy the condition.
print("\nSalary above 30000 = ", salary[salary > 30000])
print("\nSalary below or equal to 20000 =  ", salary[salary <= 20000])





		 IMPORTANT NUMPY METHODS:

Median:  77.5

Original (before sorting):   [ 70  80  90  60 100  75  70  90]

Sorted (after sorting) :  [ 60  70  70  75  80  90  90 100]

Unique values:  ['Ahmedabad' 'Bhavnagar' 'Delhi']

  (array([1, 2, 4]),)

Salary above 30000 =  [35000 50000 60000]

Salary below or equal to 20000 =   [20000 18000]
