In [14]:
import numpy as np

# np.argmax()  Meaning: Finds the index of the largest value.
marks = np.array([65, 82, 91, 74])

print(np.argmax(marks))



2


In [15]:
# flatten() and Ravel() -> both converts multidimensional array to 1D array
# iMP: Changing the raveled array can affect the original array.

# Method	          Result	                  Memory
# flatten()	       1D copy	               More memory
# ravel()	         1D view                 when possible	Less memory


#                       Flatten() -> creates a copy
arr = np.array([[1,2],[3,4]])
res = arr.flatten()
res[0] = 100
print(res)
print(arr) # -> Original array is not effected



[100   2   3   4]
[[1 2]
 [3 4]]


In [16]:
# flatten() → COPY → original usually NOT affected

# ravel() → VIEW when possible → original CAN be affected

#                           Ravel()
ans = arr.ravel()

ans[3] = 74
print(ans)
arr #->because ravel returns a View,  value is also changed in original array

[ 1  2  3 74]


array([[ 1,  2],
       [ 3, 74]])

In [ ]:
# np.linspace(start, endm step) ->  It is used to create a specified number of evenly spaced values between a start and end value.

# arange()	                      linspace()
# You specify the step       	You specify the number of values
# np.arange(0, 10, 2)	         np.linspace(0, 10, 5)
# [0, 2, 4, 6, 8]	              [0, 2.5, 5, 7.5, 10]

# Easy memory trick:

# arange → how much to jump
# linspace → how many values


ar  = np.linspace(0,10,5)
ar

# np.linspace() generates a specified number of evenly spaced values over a given interval.

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
# transpose() / .T

# Transpose is used to change the rows into columns and columns into rows.

arr1 = np.array([[1,2,3], [4,5,6]])
print("Original: \n", arr1)
print("\nTranspose \n", arr1.transpose())
# or
# print(arr1.T)

Original: 
 [[1 2 3]
 [4 5 6]]

Transpose 
 [[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# nditer() -> makes it easy to iterate through every individual element, even in multidimensional arrays.

for x in np.nditer(arr1):
  print(x)

# nditer() → individual elements

1
2
3
4
5
6


In [ ]:
# ndenumerate() gives you both the position and the value
arr2 = np.array([[10,20], [30,40]])
for index,value in np.ndenumerate(arr2):
  print(index, value)

# nditer() → iterates through every element of an array.
# ndenumerate() → gives the index and value while iterating.

(0, 0) 10
(0, 1) 20
(1, 0) 30
(1, 1) 40


In [ ]:
# np.argmax() → gives the position (index) of the largest value
# np.argmin() → gives the position (index) of the smallest value


#                 0   1   2    3   4
marks = np.array([45, 78, 92, 33, 85])

print(np.argmax(marks)) #-> For position
print(np.max(marks)) #-> For actual value

print(np.argmin(marks))
print(np.min(marks))

2
92
3
33


In [34]:
# np.sqrt() is used to find the square root of each element in a NumPy array.
a = np.array([4,9,16,25,36])
res = np.sqrt(a)
res

array([2., 3., 4., 5., 6.])