In [29]:
import numpy as np

#create an ndarray from list
data =[1,2,3,4,5]
array = np.array(data)

print([1,2,3,4,5])
# no commas between numbers, hat's how you visually tell a NumPy array apart from a Python list
print(array)
print(type(array)) #type-> numpy.ndarray

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [30]:
# Numpy array must have same datatype.
# If we mix int with string/float, everythng gets converted to string/float.
ar = np.array([1,2,3,4,'99.9'])


ar

array(['1', '2', '3', '4', '99.9'], dtype='<U21')

In [31]:
# dtype forcec a specific data type
arr = np.array([1,2,3], dtype=float)
arr

array([1., 2., 3.])

In [32]:
# Topic 2: Accessing Elements (Indexing)

# arr[index]              # 1-D array
# arr[row, col]           # 2-D array
# arr[dim1, dim2, dim3]   # 3-D array
# arr[-1]                 # negative indexing → from the end


In [33]:
#        1D Array
ar = np.array([10,20,40,74])
print(ar[0]) #First Element
print(ar[3]) #Last Element

10
74


In [34]:
#       2D Array

ar2d = np.array([[1,2,3,4], [5,6,7,8]])
print(ar2d[0, 1]) # 0th row , 1st element, also [-2, -3]
print(ar2d[1, 2]) # 1st row , 2nd element, also grid[-1, -3]
print(ar2d[0, -2]) #0th row, last 2nd element

2
7
3


In [35]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a[1,1,1] #->a[-1,-1,-2]

np.int64(11)

In [36]:
# Topic 3: Slicing [end is exclusive — it stops before that index.]

#            slicing creates a VIEW, not a copy

# 1D slicing syntax

# arr[start:end]         # elements from start to end-1
# arr[start:end:step]    # with a step size
# arr[:end]              # from beginning to end-1
# arr[start:]            # from start to the last element
# arr[::step]            # whole array, skipping by step
# arr[::-1]              # reverse the array (common trick!)

In [37]:
#          1D slicing

a = np.array([10,2,30,4,50])
print(a[1:5]) #from index 1 to index 4 ->  (5-1)
print(a[:4]) # from start to index 3 -> (4-1)
print(a[::2]) #every second element from start to end
print(a[:4:2]) #every second element from start to 3rd index (4 -1)
print(a[1::2]) #every second element from index 1 to end
print(a[::-1]) #reverse an array

[ 2 30  4 50]
[10  2 30  4]
[10 30 50]
[10 30]
[2 4]
[50  4 30  2 10]


In [38]:
arr2d = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10]])

arr2d[1, 1:4] #1st row, 1 to 4-1 = 3 columns
print(arr2d[0:1, 1:3]) #1st row, from 1st index to (3-1) 2nd index
arr2d[:, 1:4] #both rows, from 1st index to (4-1) 3rd index
arr2d

[[2 3]]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
arr = np.array([1,2,3,4,5])
sub = arr[0:2]
sub[0] = 74
arr

array([74,  2,  3,  4,  5])

In [ ]:
#                     SHAPE
# shape tells you how many elements exist in each dimension of an array

# ndim

# Returns just the count of dimensions

In [45]:
a = np.array([1,2,3])
print("1D array: ", a.shape) # 3 rows
print("1D array dimension : ", a.ndim)

b = np.array([[7,8,9], [4,5,6]])
print("2D array: ", b.shape) # 2rows and 3 columns
print("2D array dimension : ", b.ndim)

c = np.array([[[10, 20, 99],
               [30, 40, 88]],

              [[50, 60, 22],
              [74, 77, 11]]])
c
print("3D array: ", c.shape) #2 blocks, 2 rows (in each block), 3 columns (in each row))
print("3D array dimension : ", c.ndim)



1D array:  (3,)
1D array dimension :  1
2D array:  (2, 3)
2D array dimension :  2
3D array:  (2, 2, 3)
3D array dimension :  3
