In [14]:
import numpy as np

# np.argmax()  Meaning: Finds the index of the largest value.
marks = np.array([65, 82, 91, 74])

print(np.argmax(marks))



2


In [15]:
# flatten() and Ravel() -> both converts multidimensional array to 1D array
# iMP: Changing the raveled array can affect the original array.

# Method	          Result	                  Memory
# flatten()	       1D copy	               More memory
# ravel()	         1D view                 when possible	Less memory


#                       Flatten() -> creates a copy
arr = np.array([[1,2],[3,4]])
res = arr.flatten()
res[0] = 100
print(res)
print(arr) # -> Original array is not effected



[100   2   3   4]
[[1 2]
 [3 4]]


In [16]:
# flatten() → COPY → original usually NOT affected

# ravel() → VIEW when possible → original CAN be affected

#                           Ravel()
ans = arr.ravel()

ans[3] = 74
print(ans)
arr #->because ravel returns a View,  value is also changed in original array

[ 1  2  3 74]


array([[ 1,  2],
       [ 3, 74]])